name: "Publish performance report"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to comment'
        required: true
        type: number
  pull_request_review:
    types: [ submitted ]

env:
  GIT_CONFIG_GLOBAL: "/root/.gitconfig" # fix path in container (https://github.com/actions/runner/issues/2033)
  PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}

jobs:
  publish-report:
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: write
      packages: read

    steps:
      - name: "Try fetch performance comparison report"
        id: "cache-report"
        uses: "actions/cache/restore@v4"
        with:
          key: "perf-report-pr-${{ env.PR_NUMBER }}"
          path: "performance-report.md"

      - name: "Update cache for performance comparison report"
        if: ${{ steps.cache-report.outputs.cache-hit != 'true' }}
        uses: "./.github/workflows/performance.yml"

      - name: "Try fetch performance comparison report"
        if: ${{ steps.cache-report.outputs.cache-hit != 'true' }}
        uses: "actions/cache/restore@v4"
        with:
          key: "perf-report-pr-${{ env.PR_NUMBER }}"
          path: "performance-report.md"
          fail-on-cache-miss: true

      - uses: "mshick/add-pr-comment@v2"
        with:
          message-path: "performance-report.md"
          message-id: "performance-comment-pr-${{ env.PR_NUMBER }}"
          refresh-message-position: true