name: "Deploy docs"

on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: '3.x'

      - name: "Install requirements"
        run: "pip install -r doc/common/requirements.txt"

      - name: "Build site"
        run: "mkdocs build --strict --site-dir ./site"

      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./site"

  deploy:
    needs: ["build"]
    permissions:
      pages: "write"
      id-token: "write"

    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy to GitHub Page"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
