name: "Test"

on:
  workflow_call:
    inputs:
      base_ref:
        description: 'The base ref of the pull request'
        type: string
        required: false
        default: ${{ github.event.repository.default_branch }} # По умолчанию - master
      head_ref:
        description: 'The head ref of the pull request'
        type: string
        required: false
        default: ${{ github.ref }} # По умолчанию - текущая ветка

env:
  GIT_CONFIG_GLOBAL: "/root/.gitconfig" # fix path in container (https://github.com/actions/runner/issues/2033)

jobs:

  ### LINT ###

#  lint:
#    runs-on: "ubuntu-latest"
#    container:
#      image: "ghcr.io/tarantool/sdvg-ci:0.0.1"
#    steps:
#      - uses: "actions/checkout@v4"
#
#      - name: "Run linter"
#        run: "golangci-lint run --print-issued-lines=false --out-format code-climate:lint.json,line-number --timeout 5m"
#
#      - uses: "actions/upload-artifact@v4"
#        with:
#          name: "codequality"
#          path: "lint.json"

  ### UNIT ###

#  unit:
#    runs-on: "ubuntu-latest"
#    container:
#      image: "ghcr.io/tarantool/sdvg-ci:0.0.1"
#    steps:
#      - uses: "actions/checkout@v4"
#
#      - name: "Run unit tests"
#        run: "make test/unit"

  ### COVER ###

#  cover:
#    runs-on: "ubuntu-latest"
#    container:
#      image: "ghcr.io/tarantool/sdvg-ci:0.0.1"
#    steps:
#      - uses: "actions/checkout@v4"
#
#      - name: "Measuring test coverage"
#        run: "make test/cover"
#
#      - name: "Upload coverage to Coveralls"
#        uses: "coverallsapp/github-action@v2"
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          file: "coverage.out"
#          format: "golang"

  ### PERFORMANCE ###

  performance:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/hoodiehuuuuu/sdvg-ci:0.0.1"
    permissions:
      pull-requests: write
      packages: read

    steps:
      - uses: "actions/checkout@v4"

#      - name: "Checkout master branch"
#        uses: "actions/checkout@v4"
#        with:
#          ref: ${{ inputs.head_ref }}
#          path: "master_branch"

      # Запускаем бенчмарки на ветке PR

#      - name: "Run benchmarks on master branch"
#        run: |
#          make test/performance > performance.txt
#          ./build/ci/go_bench_to_metrics.sh performance.txt master-performance.txt
#        working-directory: "master_branch"

      - name: "Run benchmarks on PR branch"
        run: |
          make test/performance > performance.txt
          ./build/ci/go_bench_to_metrics.sh performance.txt pr-performance.txt

      - uses: "xSAVIKx/artifact-exists-action@v0"
        id: "check"
        with:
          name: "benchmark-master"

      - name: Get or create master benchmark
#        if
        run: "echo ${{ steps.check.outputs.exists }}"

#      - name: "Compare results"
#        run: |
#          ./pr_branch/build/ci/compare_metrics.sh ./master_branch/master-performance.txt ./pr_branch/pr-performance.txt --allowed-inaccuracy=5 --alert-threshold=20 > performance-report.md
#
#      - uses: mshick/add-pr-comment@v2
#        with:
#          message-path: "performance-report.md"